
package net.webservicex;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.8
 * 2015-03-17T12:51:09.891+01:00
 * Generated source version: 2.7.8
 * 
 */
public final class TranslateServiceHttpGet_TranslateServiceHttpGet_Client {

    private static final QName SERVICE_NAME = new QName("http://www.webservicex.net", "TranslateService");

    private TranslateServiceHttpGet_TranslateServiceHttpGet_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = TranslateService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        TranslateService ss = new TranslateService(wsdlURL, SERVICE_NAME);
        TranslateServiceHttpGet port = ss.getTranslateServiceHttpGet();  
        
        {
        System.out.println("Invoking translate...");
        java.lang.String _translate_languageMode = "";
        java.lang.String _translate_text = "";
        java.lang.String _translate__return = port.translate(_translate_languageMode, _translate_text);
        System.out.println("translate.result=" + _translate__return);


        }

        System.exit(0);
    }

}
